mod utils;


fn main() {
    let test_id: &str = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjhmNDMyMDRhMTc5MTVlOGJlN2NjZDdjYjI2NGRmNmVhMzgzYzQ5YWIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXNzYXNzaW4tOGM3MDQiLCJhdWQiOiJhc3Nhc3Npbi04YzcwNCIsImF1dGhfdGltZSI6MTYyNTUyNzAyMywidXNlcl9pZCI6InJZWFhUaVdLUGFkbHdidzZWcDZvMER1T0xCSTMiLCJzdWIiOiJyWVhYVGlXS1BhZGx3Ync2VnA2bzBEdU9MQkkzIiwiaWF0IjoxNjI1NTI3MDIzLCJleHAiOjE2MjU1MzA2MjMsImVtYWlsIjoiaW5mb0BrdHJ1b25nLmRldiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJpbmZvQGt0cnVvbmcuZGV2Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.PHOod4B6eBUrpZkyb8OmRPpp6XdBIv44WWtprda_WoSBwcqHxH1yQ2oTS6YVz1wHCUOABGNcmzOsS8kPPObVzM1ok0XbgGMLTcl6k46YKrctq5hYIPrkrjbgKB1dU8GqaldBhv1vxDgSVez83WphYkLPRH7UCUNXQItPzcmcJ4AYEM256gFlGtE4XwTe_S_cepGT9yGIPKeKhDNVRXnhXTuwHceEwpWIkzk_7Q3gG1FyvZSJkrNmTo6Es6poekArPgttTDuX6wIlXqBzV7hxDoeXsrU2PKjo7UKYAf5BtG_g0tNgffuAb8_zF1d_8L8lNd_dASrl4OwQ0hly2TDL1g";
    let validator = utils::auth::Validator::new();
    validator.validate_token(test_id);
}
